on: push
name: 🚀 Deploy website on push
jobs:
  # 第一個階段
  build:
    name: 🎉 Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to Server forward
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.forward_plesk_ftp_server }}
        username: ${{ secrets.forward_plesk_ftp_username }}
        password: ${{ secrets.forward_plesk_ftp_password }}
        server-dir: /httpdocs/maxwebiotcicd/

# 第二個階段 hpanel
  #   name: 🎉 Deploy Production
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: 📂 Sync files to Server hpanel
  #     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  #     with:
  #       server: ${{ secrets.hpanel_ftp_server }}
  #       username: ${{ secrets.hpanel_ftp_username }}
  #       password: ${{ secrets.hpanel_ftp_password }}
  #       server-dir: /public_html/bitbucketcicd/

# 第二個階段 ideathon
    # name: 🎉 Deploy Production
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    # - name: 📂 Sync files to Server ideathon
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: ideathon.leeyao.com
    #     username: ${{ secrets.dedicated_ftp_username }}
    #     password: ${{ secrets.dedicated_ftp_password }}
    #     server-dir: /httpdocs/bitbucketcicd/

# 第二個階段 ssh
  # deploy:
  #   name: 🎉 Deploy Production
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: 📂 Deploy to Server 2
  #       uses: easingthemes/ssh-deploy@main
  #       with:
  #           SSH_PRIVATE_KEY: ${{ secrets.ssh_hpanel_private_key }}
  #           ARGS: "-rlgoDzvc -i --delete"
  #           REMOTE_HOST: ${{ secrets.ssh_hpanel_host }}
  #           REMOTE_PORT: ${{ secrets.ssh_hpanel_port }}
  #           REMOTE_USER: ${{ secrets.ssh_hpanel_user }}
  #           TARGET: ${{ secrets.ssh_hpanel_target }}
  #           EXCLUDE: "/dist/, /node_modules/"